name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  infra-as-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: arquitetura-upa-atualizada
          template: infra-template.yaml
          no-fail-on-empty-changeset: 1
          no-execute-changeset: 1
          
