name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  infra-as-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_ORG }}
          aws-region: ${{ secrets.AWS_REGION_ORG }}

      - name: deploy cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: arquitetura-upa-atualizada
          template: cloudformation.yaml
          no-fail-on-empty-changeset: 1
          no-execute-changeset: 1
      
  call-lambdas-workflow:
    needs: infra-as-code
    uses: Grupo-5-Projeto/lambdas/.github/workflows/deploy.yml@main
    secrets: inherit

  instances-config:
    needs: infra-as-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          cd ansible
          echo "${{secrets.KEY_PEM_ORG}}" > urubu100-key.pem
          chmod 400 urubu100-key.pem
          ansible-playbook -i inventory.ini playbook.yaml 